// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::Utopia::MeshFilter> :
    TypeInfoBase<Ubpa::Utopia::MeshFilter>
{
#ifdef UBPA_USREFL_NOT_USE_NAMEOF
    static constexpr char name[25] = "Ubpa::Utopia::MeshFilter";
#endif
    static constexpr AttrList attrs = {};
    static constexpr FieldList fields = {
        Field {TSTR("mesh"), &Type::mesh},
    };
};

