// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::Utopia::MeshFilter>
    : Ubpa::USRefl::TypeInfoBase<Ubpa::Utopia::MeshFilter>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"mesh", &Ubpa::Utopia::MeshFilter::mesh},
    };
};

