// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::Utopia::MeshRenderer>
    : Ubpa::USRefl::TypeInfoBase<Ubpa::Utopia::MeshRenderer>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"materials", &Ubpa::Utopia::MeshRenderer::materials},
    };
};

