// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::Utopia::Skybox>
    : Ubpa::USRefl::TypeInfoBase<Ubpa::Utopia::Skybox>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"material", &Ubpa::Utopia::Skybox::material},
    };
};

