// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::Utopia::LuaScriptQueue> :
    TypeInfoBase<Ubpa::Utopia::LuaScriptQueue>
{
#ifdef UBPA_USREFL_NOT_USE_NAMEOF
    static constexpr char name[29] = "Ubpa::Utopia::LuaScriptQueue";
#endif
    static constexpr AttrList attrs = {};
    static constexpr FieldList fields = {
        Field {TSTR("value"), &Type::value},
    };
};

