{
    "hlslFile":"94aa0330-a09e-47f4-8799-da329e55fa7c",
    "shaderName":"StdPipeline/Irradiance",
    "passes":[
        {
            "vertexName":"VS",
            "fragmentName":"PS"
        }
    ],
    "targetName":"5_0",
    "rootParameters":[
        {
            "__INDEX":0,
            "__CONTENT":[
                {
                    "RangeType":1,
                    "NumDescriptors":1,
                    "BaseShaderRegister":0,
                    "RegisterSpace":0
                }
            ]
        },
        {
            "__INDEX":2,
            "__CONTENT":{
                "DescriptorType":0,
                "ShaderRegister":0,
                "RegisterSpace":0
            }
        }
    ]
}