{
    "hlslFile":"bdd78e15-6ec2-40fe-b7ce-93ce142d19a7",
    "shaderName":"StdPipeline/Skybox",
    "passes":[
        {
            "vertexName":"VS",
            "fragmentName":"PS"
        }
    ],
    "targetName":"5_0",
    "rootParameters":[
        {
            "__INDEX":0,
            "__CONTENT":[
                {
                    "RangeType":1,
                    "NumDescriptors":1,
                    "BaseShaderRegister":0,
                    "RegisterSpace":0
                }
            ]
        },
        {
            "__INDEX":2,
            "__CONTENT":{
                "DescriptorType":0,
                "ShaderRegister":0,
                "RegisterSpace":0
            }
        }
    ]
}