{
    "hlslFile":"92bd0b61-5844-4d20-95ba-4bb17636ae74",
    "shaderName":"StdPipeline/Transparent",
    "targetName":"5_0",
    "rootParameters":[
        {
            "__INDEX":0,
            "__CONTENT":[
                {
                    "RangeType":1,
                    "NumDescriptors":1,
                    "BaseShaderRegister":0,
                    "RegisterSpace":0
                }
            ]
        },
        {
            "__INDEX":0,
            "__CONTENT":[
                {
                    "RangeType":1,
                    "NumDescriptors":1,
                    "BaseShaderRegister":1,
                    "RegisterSpace":0
                }
            ]
        },
        {
            "__INDEX":0,
            "__CONTENT":[
                {
                    "RangeType":1,
                    "NumDescriptors":1,
                    "BaseShaderRegister":2,
                    "RegisterSpace":0
                }
            ]
        },
        {
            "__INDEX":0,
            "__CONTENT":[
                {
                    "RangeType":1,
                    "NumDescriptors":1,
                    "BaseShaderRegister":3,
                    "RegisterSpace":0
                }
            ]
        },
        {
            "__INDEX":0,
            "__CONTENT":[
                {
                    "RangeType":1,
                    "NumDescriptors":3,
                    "BaseShaderRegister":4,
                    "RegisterSpace":0
                }
            ]
        },
        {
            "__INDEX":2,
            "__CONTENT":{
                "DescriptorType":0,
                "ShaderRegister":0,
                "RegisterSpace":0
            }
        },
        {
            "__INDEX":2,
            "__CONTENT":{
                "DescriptorType":0,
                "ShaderRegister":1,
                "RegisterSpace":0
            }
        },
        {
            "__INDEX":2,
            "__CONTENT":{
                "DescriptorType":0,
                "ShaderRegister":2,
                "RegisterSpace":0
            }
        },
        {
            "__INDEX":2,
            "__CONTENT":{
                "DescriptorType":0,
                "ShaderRegister":3,
                "RegisterSpace":0
            }
        }
    ],
    "properties":{
        "gAlbedoMap":{
            "__INDEX":22,
            "__CONTENT":"1936ed7e-6896-4ace-abd9-5b084fcfb891"
        },
        "gMetalnessMap":{
            "__INDEX":22,
            "__CONTENT":"1936ed7e-6896-4ace-abd9-5b084fcfb891"
        },
        "gNormalMap":{
            "__INDEX":22,
            "__CONTENT":"b5e7fb39-fedd-4371-a00a-552a86307db7"
        },
        "gRoughnessMap":{
            "__INDEX":22,
            "__CONTENT":"1936ed7e-6896-4ace-abd9-5b084fcfb891"
        },
        "gAlbedoFactor":{
            "__INDEX":20,
            "__CONTENT":[1,1,1]
        },
        "gRoughnessFactor":{
            "__INDEX":3,
            "__CONTENT":1
        },
        "gMetalnessFactor":{
            "__INDEX":3,
            "__CONTENT":1
        }
    },
    "passes":[
        {
            "vertexName":"VS",
            "fragmentName":"PS",
            "renderState":{
                "cullMode":3,
                "zTest":2,
                "zWrite":true,
                "blendState":{
                    "blendEnable":true
                }
            },
            "tags":{
                "LightMode":"Forward"
            },
            "queue": 2500
        }
    ]
}