// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::DustEngine::MeshRenderer>
    : Ubpa::USRefl::TypeInfoBase<Ubpa::DustEngine::MeshRenderer>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"material", &Ubpa::DustEngine::MeshRenderer::material},
    };
};

