// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::DustEngine::WorldToLocal>
    : Ubpa::USRefl::TypeInfoBase<Ubpa::DustEngine::WorldToLocal>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"value", &Ubpa::DustEngine::WorldToLocal::value},
    };
};

