// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::DustEngine::LuaScriptQueue>
	: Ubpa::USRefl::TypeInfoBase<Ubpa::DustEngine::LuaScriptQueue>
{
	static constexpr AttrList attrs = {};

	static constexpr FieldList fields = {
		Field{"value", &Ubpa::DustEngine::LuaScriptQueue::value},
	};
};

