// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::Utopia::Material>
	: Ubpa::USRefl::TypeInfoBase<Ubpa::Utopia::Material>
{
	static constexpr AttrList attrs = {};

	static constexpr FieldList fields = {
		Field{"shader", &Ubpa::Utopia::Material::shader},
		Field{"properties", &Ubpa::Utopia::Material::properties}
	};
};

