// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::DustEngine::RenderRsrcObject>
	: Ubpa::USRefl::TypeInfoBase<Ubpa::DustEngine::RenderRsrcObject>
{
	static constexpr AttrList attrs = {};

	static constexpr FieldList fields = {
		Field{Name::constructor, WrapConstructor<Ubpa::DustEngine::RenderRsrcObject()>()},
		Field{"GetInstanceID", &Ubpa::DustEngine::RenderRsrcObject::GetInstanceID},
	};
};

