// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::Utopia::Object>
	: Ubpa::USRefl::TypeInfoBase<Ubpa::Utopia::Object>
{
	static constexpr AttrList attrs = {};

	static constexpr FieldList fields = {
		Field{Name::constructor, WrapConstructor<Ubpa::Utopia::Object()>()},
		Field{"GetInstanceID", &Ubpa::Utopia::Object::GetInstanceID},
	};
};

