// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::Utopia::Translation>
    : Ubpa::USRefl::TypeInfoBase<Ubpa::Utopia::Translation>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"value", &Ubpa::Utopia::Translation::value},
    };
};

