// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::UECS::AccessMode>
    : Ubpa::USRefl::TypeInfoBase<Ubpa::UECS::AccessMode>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"LAST_FRAME", Ubpa::UECS::AccessMode::LAST_FRAME},
        Field{"WRITE", Ubpa::UECS::AccessMode::WRITE},
        Field{"LATEST", Ubpa::UECS::AccessMode::LATEST},
    };
};

