// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<Ubpa::DustEngine::Material>
	: Ubpa::USRefl::TypeInfoBase<Ubpa::DustEngine::Material>
{
	static constexpr AttrList attrs = {};

	static constexpr FieldList fields = {
		Field{"shader", &Ubpa::DustEngine::Material::shader},
		Field{"texture2Ds", &Ubpa::DustEngine::Material::texture2Ds},
		Field{"textureCubes", &Ubpa::DustEngine::Material::textureCubes},
	};
};

